# Generalised Sample Size Calculations


## Prerequisits

### Define bandits

```{r}

balanced <- function(i, j, k, l, chooser_params) {

  n <- i + j + k + l

  if (n %% 2) {
    action <- sample(c(1, 2), size = 1)
  } else {
    if (i + j < k + l) {
      action <- 1
    } else {
      action <- 2
    }
  }

  return(action)
}


thomper <- function( i, j, k, l, chooser_params ) {

  sample.c <- rbeta(1, i + prior.i, j + prior.j)
  sample.n <- rbeta(1, k + prior.k, l + prior.l)

  if (sample.c > sample.n) {
    return(1)
  } else {
    return(2)
  }
}


foo <- function(i, j, k, l) {
  # https://gwern.net/doc/statistics/decision/1933-thompson.pdf
  numer <- 0

  for (a in 0:(i)) {
    numer <- numer + (choose(i + k - a, k) * choose(j + l + 1 + a, l))
  }
  denom <- choose(i + j + k + l + 2, k + l + 1)
  sum <- numer / denom

  return(sum)
}


tw <- function(i, j, k, l, chooser_params) {

  c <- chooser_params

  prob <- tryCatch(
    {
      min(foo(i + prior.i, j + prior.j, k + prior.k, l + prior.l), 1)
    },
    error = function(cond) {
      expected.c <- (i + prior.i) / (i + prior.i + j + prior.j)
      expected.n <- (k + prior.k) / (k + prior.k + l + prior.l)

      if (expected.c > expected.n) {
        1
      } else {
        0
      }
    }
  )

  if (is.na(prob)) {
    sample.c <- rbeta(1, i + prior.i, j + prior.j)
    sample.n <- rbeta(1, k + prior.k, l + prior.l)

    if (sample.c > sample.n) {
      prob <- 1
    } else {
      prob <- 0
    }
  }

  quant <- (prob**c) / (prob**c + (1 - prob)**c)

  #print(paste("c:", c, "prob:", prob, "quant:", quant, "i:", i, "j:",j ,"k:", k,"l:", l))
  if (is.na(quant)) {
    print(paste(i, j, k, l))
  }

  action <- sample(c(1, 2), 1, prob = c(quant, 1 - quant))

  return(action)
}

DTL <- function(i, j, k, l, chooser_params) {
  numb_of_immigrants <- chooser_params

  done = FALSE
  while(1 - done) {
    urn <- c(5, 2 + numb_of_immigrants - j, 2 + numb_of_immigrants - l)
    #print(urn)
    ball <- sample(c(0, 1, 2), 1, prob = c(urn / sum(urn)))
    if (ball == 0) {
      numb_of_immigrants <- numb_of_immigrants + 1
    } else {
      done <- TRUE
    }
  }
  return(c(ball, numb_of_immigrants))
}


g <- function(alpha, x, y) {
  if (x == 1) {
    return(0)
  } else if (x == 0) {
    return(1)
  } else {
    numer <- y * (y / x)**alpha
    denom <- y * (y / x)**alpha + (1 - y) * ((1 - y) / (1 - x))**alpha
    return(numer / denom)
  }
}


DBCD <- function(i, j, k, l, chooser_params) {

  alpha <- chooser_params

  n <- i + j + k + l
  if (n < 4) {
    if (n %% 2 == 1) {
      return(1)
    } else {
      return(2)
    }
  } else {

    p_hat_m_1 <- (i + 0.5) / (i + j + 1)
    p_hat_m_2 <- (k + 0.5) / (k + l + 1)

    q_hat_m_1 <- 1 - p_hat_m_1
    q_hat_m_2 <- 1 - p_hat_m_2

    p_hat_m <- q_hat_m_2 / (q_hat_m_2 + q_hat_m_1)

    prob <- g(alpha, (i + j) / n, p_hat_m)

    #print(prob)

    action <- sample(c(1, 2), 1, prob = c(prob, 1 - prob))
    return(action)
  }
}


ebm <- function(i, j, k, l, chooser_params) {

  trial_size <- chooser_params
  patient <- i + j + k + l

  if (patient < trial_size) {
    if (patient %% 2) {
      return(sample(c(1, 2), size = 1))
    } else {
      if (i + j < k + l) {
        return(1)
      } else {
        return(2)
      }
    }
  } else {
    expected.c <- (prior.i + i) / (prior.i + i + prior.j + j)
    expected.n <- (prior.k + k) / (prior.k + k + prior.l + l)

    if (expected.c > expected.n) {
      return(1)
    } else {
      return(2)
    }
  }
}



```


### Trial Infrastructure

```{r}

one_run <- function(n, chooser, chooser_params, alpha) {

  i <- 0
  j <- 0
  k <- 0
  l <- 0

  # set the true probability of success
  p.c <- rbeta(1, prior.i, prior.j)
  p.n <- rbeta(1, prior.k, prior.l)

  correctly_reject_nulls <- c()
  is_successes <- c()

  for (m in 1:n) {

    # use the chooser function to pick an action
    # in this case, it should return 1 or 2
    action <- chooser(i, j, k, l, chooser_params)
    if (length(action) != 1) {
      chooser_params <- action[2]
      action <- action[1]
    }

    if (action == 1) {

      # decide whether or not the treatment is a success
      sample <- rbinom(1, 1, p.c)

      if (sample == 1) {
        # success!
        i <- i + 1
      } else if (sample == 0) {
        # failure
        j <- j + 1
      }
    } else {
      # decide whether or not the treatment is a success
      sample <- rbinom(1, 1, p.n)

      if (sample == 1) {
        # success!
        k <- k + 1
      } else if (sample == 0) {
        # failure
        l <- l + 1
      }
    }

    xtab <- as.table(rbind(c(i, j), c(k, l)))
    dimnames(xtab) <- list(
      group = c("grp1", "grp2"),
      success = c("yes", "no")
    )

    null_rejected <- tryCatch(
      {
        test <- prop.test(xtab)
        test["p.value"] < alpha
      },
      error=function(cond) {
        FALSE
      }
    )
    if (is.na(null_rejected)) {
      null_rejected <- FALSE
    }
    # power is based on _correctly_ rejecting the null
    # we must ignore rejections where the sign is wrong
    p.c_hat <- i / (i + j)
    p.n_hat <- k / (k + l)
    incorrect_direction <- (p.c_hat > p.n_hat) != (p.c > p.n)
    correctly_reject_null <- null_rejected
    if (null_rejected && incorrect_direction) {
      correctly_reject_null <- FALSE
    }

    correctly_reject_nulls <- append(correctly_reject_nulls, correctly_reject_null)
    is_successes <- append(is_successes, sample)
  }

  return(rbind(correctly_reject_nulls, is_successes))
}


simulator <- function(numb_of_sims, numb_of_patients, runner, chooser, chooser_params, alpha) {

  runs <- array(0, dim = c(2, numb_of_patients))

  for (iter in 1:(numb_of_sims)) {

    run_results <- runner(numb_of_patients, chooser, chooser_params, alpha)
    runs <- runs + (run_results - runs) / (iter + 1)
  }

  return(runs)
}

```

## Body

```{r}

# setup parameters
numb_of_sims <- 500
numb_of_patients <- 2**9

prior.i <- 100
prior.j <- 100
prior.k <- 3
prior.l <- 1

power_threshold <- 0.8
alpha <- 0.05

# plot beta distributions
x1 <- seq(0, 1, length=1000)
y1 <- dbeta(x1, prior.i, prior.j)
plot(x1, y1,
     type = "l", col = "red", main = "Plot of Priors",
     ylab = "Probability density", xlab = "Actual Proportion")

x2 <- seq(0, 1, length = 1000)
y2 <- dbeta(x1, prior.k, prior.l)
lines(x2, y2, col = "blue")
legend(x = "topright",
       legend = c(paste0("Beta(", prior.i, ",", prior.j, ")"),
                  paste0("Beta(", prior.k, ",", prior.l, ")")),
       lty = 1, col = c("red", "blue"))

```




```{r}

chooser <- "DBCD"
chooser_params <- 2

# simulate the clinical trials
sim_output <- simulator(numb_of_sims, numb_of_patients, one_run, get(chooser), chooser_params, alpha)

```

```{r}

# plot the expected power for each sample size

png("sample size vs power for DBCD(2); B(100,100) & B(1,3).png",
    units = "in", width = 5, height = 4, res = 300)

x <- 1:numb_of_patients
y <- sim_output[1, ]

plot(x, y,
     ylim = c(0, 1), cex = 0.25,
     ylab = "Expected power", xlab = "Sample size",
     main = "Sample Size vs Power for DBCD(2)")

# find the sample size that give the power_threshold set earlier
abline(h = power_threshold)
optimal_sample_size <- sum(y < power_threshold)
optimal_sample_size
abline(v = optimal_sample_size)

dev.off()

```



```{r}

add_to_csv <- function(numb_of_sims, numb_of_patients, runner, chooser, chooser_params, alpha) {

  sim_output <- simulator(numb_of_sims, numb_of_patients, runner, get(chooser), chooser_params, alpha)

  orders_of_magitude <- floor(log(numb_of_patients, 2))

  for (i in 1:orders_of_magitude) {
    sample_size <- 2**i
    df <- data.frame(
      "timestamp" = Sys.Date(),
      "number of sims" = numb_of_sims,
      "sample size" = sample_size,
      "chooser" = chooser,
      "chooser_params" = chooser_params,
      "prior.i" = prior.i,
      "prior.j" = prior.j,
      "prior.k" = prior.k,
      "prior.l" = prior.l,
      "power" = sim_output[1,][sample_size],
      "ENS" = mean(sim_output[2,1:sample_size])
    )
    write.table(df, "power and ENS for adaptive trials.csv",
                append = TRUE, sep = ",",
                col.names = FALSE, row.names = FALSE)
  }
}

```


```{r}

priors <- rbind(
  c(1, 1),
  c(100, 100),
  # c(100, 1),
  # c(1, 100),
  c(3, 1),
  # c(3, 2),
  # c(6, 4),
  # c(10, 1),
  # c(10, 10),
  # c(420, 300),
  # c(600, 500),
  c(1000, 10),
  c(1010, 10)
)

choosers <- rbind(
  c("balanced", "NA")
)

# choosers <- rbind(
#   c("balanced", "NA"),
#   c("thomper", "NA"),
#   c("DTL", 0),
#   c("DTL", 2),
#   c("DTL", 6),
#   c("DBCD", 0),
#   c("DBCD", 2),
#   c("DBCD", 4),
#   c("tw", 0.5)
# )


# choosers <- rbind(
#   c("tw", 1/3),
#   c("tw", 2/3),
#   c("tw", 1/5),
#   c("tw", 4/5),
#   c("tw", 1/9),
#   c("tw", 8/9)
# )


for (x in 1:dim(priors)[1]) {
  for (y in 1:dim(priors)[1]) {
    if (y >= x) {
      prior.i <- priors[x, 1]
      prior.j <- priors[x, 2]
      prior.k <- priors[y, 1]
      prior.l <- priors[y, 2]
      print(paste(prior.i, prior.j, prior.k, prior.l))

      for (z in 1:dim(choosers)[1]) {
        print(paste(choosers[z, ][1], choosers[z, ][2]))
        add_to_csv(10000, 2**8, one_run, choosers[z, ][1], as.numeric(choosers[z, ][2]), alpha)
      }
    }
  }
}
```




```{r}

# pull in data
df <- read.csv("power and ENS for adaptive trials.csv")

# force type conversion
df$power <- as.numeric(df$power)
df$ENS <- as.numeric(df$ENS)

# filter data frame
df <- df[df$sample.size == 2**9, ]
df <- df[df$number.of.sims == 1000, ]
df <- df[df$prior.i == 1, ]
df <- df[df$prior.j == 1, ]
df <- df[df$prior.k == 1, ]
df <- df[df$prior.l == 1, ]

# group by allocation method and average across different sims of the same thing
df <- aggregate(df[, 10:11], by=list(paste(df$chooser, df$chooser_params)), FUN=mean)

# plot results on a scatter plot
plot(df$power, df$ENS,
     xlim = c(0, 1), ylim = c(0, 1),
     main = "Pareto frontier", sub = "Expected Power vs Expected Benifit",
     xlab = "Expected Power", ylab = "Expected Proportion of Successes")

# label all points
#text(df$power, df$ENS - 0.01, labels = df$Group.1)

# find points on the Pareto frontier
df <- df[order(df$power, decreasing = TRUE), ]
df <- df[which(df$ENS == cummax(df$ENS)), ]
lines(df$power, df$ENS)

# label points on the Pareto frontier
text(df$power + 0.012, df$ENS + 0.012, labels = df$Group.1)
```

