# Montecarlo Sample Size Calculations

## Define functions

```{r}

balanced <- function( i, j, k, l, chooser_params ) {

    n <- i + j + k + l

    if (n%%2) {
        action <- sample(c(1,2), size=1)
    }
    else {
        if (i + j < k + l) {
            action <- 1
        } else {
            action <- 2
        }
    }

    return(action)
}


one_run <- function(n, chooser, chooser_params, alpha) {

    i <- 0
    j <- 0
    k <- 0
    l <- 0

    # set the true probability of success
    p.c <- rbeta( 1, prior.i, prior.j )
    p.n <- rbeta( 1, prior.k, prior.l )

    correctly_reject_nulls <- c()

    for (m in 1:n) {

        # use the chooser function to pick an action
        # in this case, it should return 1 or 2
        action <- chooser( i, j, k, l, chooser_params )
        if (length(action)!=1) {
            chooser_params <- action[2]
            action <- action[1]
        }

        if (action == 1) {

            # decide whether or not the treatment is a success
            sample <- rbinom(1, 1, p.c)

            if (sample == 1) {
                # success!
                i <- i + 1
            } else if (sample == 0) {
                # failure
                j <- j + 1
            }
        } else {
            
            # decide whether or not the treatment is a success
            sample <- rbinom(1, 1, p.n)

            if (sample == 1) {
                # success!
                k <- k + 1
            } else if (sample == 0) {
                # failure
                l <- l + 1
            }
        }

        xtab <- as.table(rbind(c(i, j), c(k, l)))
        dimnames(xtab) <- list(
            group = c("grp1", "grp2"),
            success = c("yes", "no")
        )


        null_rejected <- tryCatch(
            {
                test <- prop.test(xtab)
                test["p.value"] < alpha
            },
            error=function(cond) {
                FALSE
            }
        )
        if (is.na(null_rejected)) {
            null_rejected <- FALSE
        }
        # power is based on _correctly_ rejecting the null
        # we must ignore rejections where the sign is wrong
        p.c_hat <- i/(i+j)
        p.n_hat <- k/(k+l)
        incorrect_direction <- (p.c_hat > p.n_hat) != (p.c > p.n)
        correctly_reject_null <- null_rejected
        if (null_rejected & incorrect_direction) {
            correctly_reject_null <- FALSE
        }

        correctly_reject_nulls <- append(correctly_reject_nulls, correctly_reject_null)
    }

    return(correctly_reject_nulls)
}


simulator <- function(numb_of_sims, numb_of_patients, runner, chooser, chooser_params, alpha) {

    runs <- array(0, dim=numb_of_patients)
    props <- c()

    for (iter in 1:(numb_of_sims)) {
        
        correctly_reject_nulls <- runner(numb_of_patients, chooser, chooser_params, alpha)
        runs <- runs + (correctly_reject_nulls - runs)/(iter+1)
    }

    return(c(runs, props))
}


```

## Set up parameters

```{r}
numb_of_sims <- 10000
numb_of_patients <- 300

prior.i <- 100
prior.j <- 100
prior.k <- 3
prior.l <- 1

power_threshold <- 0.8
alpha <- 0.05

```

## Plot of Bayesian Priors

```{r}

png("priors.png", units = "in", width = 2, height = 2, res = 300)

x1 <- seq(0, 1, length=1000)
y1 <- dbeta(x1, prior.i, prior.j)
plot(x1, y1, type="l", col="red", main="Plot of Priors", ylab="Probability density", xlab="Actual Proportion")

x2 <- seq(0, 1, length=1000)
y2 <- dbeta(x1, prior.k, prior.l)
lines(x2, y2, col="blue")
#plot(x2, y2, type="l", col="blue", main="Plot of Prior of the Experimental Treatment", ylab="Probability density", xlab="Actual Proportion", width=5, hight=4)

#legend(x="topright", legend=c(paste0("Beta(",prior.i,",",prior.j,")")), lty=1, col=c("red"))
#legend(x="topright", legend=c(paste0("Beta(",prior.k,",",prior.l,")")), lty=1, col=c("blue"))
legend(x="topright", legend=c(paste0("Beta(",prior.i,",",prior.j,")"), paste0("Beta(",prior.k,",",prior.l,")")), lty=1, col=c("red", "blue"))

dev.off()

```

## Calculate Minimum Sufficient Sample Size

```{r}

png("power_vs_sample_size.png", units = "in", width = 5, height = 4, res = 300)

y <- simulator(numb_of_sims, numb_of_patients, one_run, balanced, NA, alpha)
x <- 1:numb_of_patients
plot(x,y, ylim=c(0,1), ylab="Expected power",xlab="Sample size",main="Simulations of Optimal Sample Size")
abline(h=power_threshold)
optimal_sample_size <- sum(y < power_threshold); optimal_sample_size
abline(v=optimal_sample_size)

dev.off()

```


```{r}

png("power_vs_sample_size.png", units = "in", width = 5, height = 4, res = 300)

plot(x,y, ylim=c(0,1), cex=0.5, ylab="Expected power",xlab="Sample size",main="Simulations of Optimal Sample Size")
abline(h=power_threshold)
optimal_sample_size <- sum(y < power_threshold); optimal_sample_size
abline(v=optimal_sample_size)



dev.off()

```
